---
abstract: 'Normalization Utilities for Amharic.'
author:
  - 'Daniel Yacob <dyacob\@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Equivalence-Amharic
provides:
  String::Equivalence::Amharic:
    file: lib/String/Equivalence/Amharic.pm
    version: '0.07'
requires:
  Regexp::Ethiopic: '0.15'
  perl: v5.6.1
resources:
  bugtracker: https://github.com/dyacob/String-Equivalence-Amharic/issues
  homepage: https://github.com/dyacob/String-Equivalence-Amharic
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dyacob/String-Equivalence-Amharic.git
version: '0.07'
x_authority: cpan:dyacob
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
